services:
  openai-service:
    build: ./OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - eleusis-network

  elly-bot-eleusis:
    build: .
    volumes:
      - .:/app
    command: node EleusisChat/Elly/Eleusis_index.js
    env_file:
      - .env

  elly-bot-yorgas:
    build: .
    volumes:
      - .:/app
    command: node EleusisChat/Elly/Yorgas_index.js
    env_file:
      - .env
 
  web_integration:
    build: ./WebIntegration
    ports:
      - "80:80"
    environment:
      - SERPAPI_KEY=your_actual_serpapi_key_here
    env_file:  # Points to a .env file for environment variables
      - .env
    networks:
      - eleusis-network

networks:
  eleusis-network:
    driver: bridge
