version: '3.8'

services:
  openai-service:
    build:
      context: ./OpenAI
    ports:
      - "6000:6000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./OpenAI:/app
    networks:
      - eleusis-network

  elly-bot:
    build:
      context: ./Elly
    command: node index.js
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:6000
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
      - ASK_CHANNEL_ID=${ASK_CHANNEL_ID}
    volumes:
      - ./Elly:/app
    networks:
      - eleusis-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none  # Disable authentication
    volumes:
      - ./MindPalace/data:/data
      - ./MindPalace/logs:/logs
      - ./MindPalace/import:/var/lib/neo4j/import
      - ./MindPalace/plugins:/plugins
    ports:
      - "7474:7474"  # Neo4j browser
      - "7687:7687"  # Bolt protocol for Neo4j
    networks:
      - eleusis-network

  mindpalace-python:
    build: ./MindPalace
    container_name: mindpalace-python
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=  # Leave password empty since auth is disabled
    volumes:
      - ./MindPalace:/app
    depends_on:
      - neo4j
    networks:
      - eleusis-network

networks:
  eleusis-network:
    driver: bridge
