version: '3.8'
services:
  openai-service:
    build: ./OpenAI
    ports:
      - "6000:6000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./OpenAI:/app
  swiper-bot:
    build: ./Swiper
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:6000
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID:-""}
    depends_on:
      - openai-service  # Add this line to ensure openai-service starts first
