version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - eleusis-network

  mindpalace-python:
    build: ./MindPalace
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=
      - NEO4J_PASSWORD=
      - PYTHONPATH=/app:/app/MindPalace
    networks:
      - eleusis-network
    depends_on:
      - neo4j

  openai-service:
    build: ./OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app:/app/MindPalace
    networks:
      - eleusis-network
    depends_on:
      - mindpalace-python

  elly-bot:
    build: ./Elly
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:6000
      - ASK_CHANNEL_ID=${ASK_CHANNEL_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
    networks:
      - eleusis-network
    depends_on:
      - openai-service

networks:
  eleusis-network:
    driver: bridge
