version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - eleusis-network

  mindpalace-python:
    build: ./MindPalace  # Ensure this points to the correct Dockerfile in the MindPalace directory
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - PYTHONPATH=/app:/app/MindPalace
    networks:
      - eleusis-network
    depends_on:
      - neo4j
    entrypoint: ["./wait-for-it.sh", "neo4j:7687", "--timeout=30", "--", "python", "main.py"]

  openai-service:
    build: ./OpenAI  # This should point to the correct Dockerfile location for OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app:/app/MindPalace  # Ensures MindPalace is in PYTHONPATH
    networks:
      - eleusis-network
    depends_on:
      - mindpalace-python
      - neo4j

      
  elly-bot:
    build: ./Elly  # Ensure this points to the correct Dockerfile in the Elly directory
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:5000
      - ASK_CHANNEL_ID=${ASK_CHANNEL_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
    networks:
      - eleusis-network
    depends_on:
      - openai-service

networks:
  eleusis-network:
    driver: bridge
