services:
  openai-service:
    build: ./OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://mindpalace:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - eleusis-network

  elly-bot:
    build:
      context: ./Elly
      dockerfile: Dockerfile
    volumes:
      - ./Elly:/app
    command: node index.js
    env_file:
      - .env
    networks:
      - eleusis-network

  mindpalace:
    build: ./MindPalace
    container_name: mindpalace
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - eleusis-network

#  fadeblaze420-bot:
#    build:
#      context: ./FadeBlaze420
#      dockerfile: Dockerfile
#    volumes:
#      - ./FadeBlaze420:/app
#    command: node index.js
#    env_file:
#     - .env
#    networks:
#      - eleusis-network

networks:
  eleusis-network:
    driver: bridge

volumes:
  neo4j_data:

