version: '3.8'

services:
  openai-service:
    build:
      context: ./OpenAI
    ports:
      - "6000:6000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./OpenAI:/app
    networks:
      - eleusis-network

  elly-bot:
    build:
      context: ./Elly
    command: node index.js
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:6000
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
      - ASK_CHANNEL_ID=${ASK_CHANNEL_ID}
    volumes:
      - ./Elly:/app
    networks:
      - eleusis-network

  # Service 3: Neo4j
  neo4j:
    image: neo4j:5.3.0
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP access to Neo4j browser
      - "7687:7687"  # Bolt protocol for Neo4j driver
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - ./MindPalace/data:/data  # Persist data
      - ./MindPalace/logs:/logs  # Persist logs
      - ./MindPalace/import:/var/lib/neo4j/import  # Folder for imports
      - ./MindPalace/plugins:/plugins  # Plugins folder
    networks:
      - eleusis-network

networks:
  eleusis-network:
    driver: bridge
