services:
  openai-service:
    build: ./OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - eleusis-network

  elly-bot:
    build:
      context: ./Elly
      dockerfile: Dockerfile
    volumes:
      - ./Elly:/app
    command: node index.js
    env_file:
      - .env
    networks:
      - eleusis-network

  fadeblaze420-bot:
    build:
      context: ./FadeBlaze420
      dockerfile: Dockerfile
    volumes:
      - ./FadeBlaze420:/app
    command: node index.js
    env_file:
      - .env
    networks:
      - eleusis-network

networks:
  eleusis-network:
    driver: bridge

