version: '3.8'

services:
  openai-service:
    build: ./OpenAI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - eleusis-network

  elly-bot:
    build: ./Elly
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_BASE_URL=http://openai-service:6000
      - ASK_CHANNEL_ID=${ASK_CHANNEL_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
    networks:
      - eleusis-network
    depends_on:
      - openai-service

  web_integration:
    build: ./WebIntegration
    ports:
      - "80:80"
    environment:
      - SERPAPI_KEY=your_actual_serpapi_key_here
    env_file:  # Points to a .env file for environment variables
      - .env
    networks:
      - eleusis-network

networks:
  eleusis-network:
    driver: bridge
