# Use an official Python runtime as a parent image
FROM python:3.10-slim

ENV PYTHONPATH=/app:/app/MindPalace

# Set environment variables
ENV NEO4J_URI=$NEO4J_URI \
    NEO4J_USER=$NEO4J_USER \
    NEO4J_PASSWORD=$NEO4J_PASSWORD

# Set the working directory in the container
WORKDIR /app

# Copy all necessary files, including main.py, to the /app directory
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["python", "main.py"]
