# Use the official Neo4j image
FROM neo4j:4.4

# Install the required plugins by setting the environment variables
ENV NEO4JLABS_PLUGINS='["apoc", "graph-data-science", "bloom"]'

# Enable file imports and procedures
ENV NEO4J_apoc_import_file_enabled=true
ENV NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
ENV NEO4J_dbms_default_listen_address=0.0.0.0

# Set the working directory in the container (if needed for custom configurations)
WORKDIR /var/lib/neo4j

# The default command will automatically start Neo4j
CMD ["neo4j"]
