# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
# These can be overridden by values provided by the Docker Compose or .env file
ENV NEO4J_URI=$NEO4J_URI \
    NEO4J_USER=$NEO4J_USER \
    NEO4J_PASSWORD=$NEO4J_PASSWORD

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Add wait-for-it script
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Run the wait-for-it script before starting the application
CMD ["/bin/bash", "-c", "/wait-for-it.sh neo4j:7687 -- python test_connection.py"]
